### ISSUE TITLE
Logger error

### ISSUE THREAD

**Issue by Boroom** [edoardottt/twitterbot2#39]
I tried to install your twitterbot using python 3.9 and 3.10 and i have the same issue. I installed the requirements.txt and everything was fine and updated the globals.oy as it is mentionned. 

You can see what happened on the screenshot.

Note : I tried to give the keyword with and without the " but I have the same issue.

![image](https://user-images.githubusercontent.com/24244481/141747619-b7304fe7-9337-4efa-88fd-2c72b83a3e5f.png)

**Comment by edoardottt** [comment]
Thank you @Boroom for the help! Appreciated the logs :)  
Just pushed an update, could you please try it and tell me if everything now is okay? If yes, I will close the issue.  
Thank you :)

**Comment by Boroom** [comment]
It's working fine thanks !
I have a question, when I'm using the "-k" parameter, is it possible to give several keywords or it's only one at a time ?

**Comment by edoardottt** [comment]
For now it's only one word, I remember there isn't an API method to search for different terms, but maybe in this way you will reach the limit cap really easy.   
Open another issue specifying the functionality, I will try to find something :)

**Comment by edoardottt** [comment]
I'm closing this issue because the problem seems solved.
