### ISSUE TITLE
Adding more keywords and choose to fav and retweet

### ISSUE THREAD

**Issue by Boroom** [edoardottt/twitterbot2#43]
Would it be possible to enter more than one keyword ?
And when a tweet is found, that would be interesting to have the choice to only fav it or only retweeting it.

**Comment by edoardottt** [comment]
Thank you for your submission.  
These features can be splitted:
1. Add the possibility to search for more than one term: e.g.: `-k security, like, pop`.
2. Add the `-nr` no retweets flag, meaning that you want only to like tweets.
3. Add the `-nl` no likes flag, meaning that you want only to retweet tweets.

**Comment by edoardottt** [comment]
Added these features in the *devel* branch, look at that code, try to run and see if everything is okay. I've done some tests and It seems okay for me. :)

**Comment by Boroom** [comment]
That's very nice I will look at it in a few hours !
And another question, is it possible to add a option where you add a flag like `-follow-user` where when you like a tweet, your bot will follow the user who sent the tweet. I don't know if it would be a good idea for you but we never know 😄

**Comment by edoardottt** [comment]
Yeah it would be good for follow 4 follow things, but I think this functionality is very limited, you will probably hit a small ban.. :/  
That's why it's not implemented.. let me know if everything work correctly :)

**Comment by Boroom** [comment]
Okay that's fine, I will test it this afternoon !
Thanks a lot 😄

**Comment by edoardottt** [comment]
@Boroom Any update? is everything okay?

**Comment by Boroom** [comment]
I tried a few hours ago and everything was fine ! Good work ! 😁

**Comment by edoardottt** [comment]
Thank you! I will close this issue and update the tool, releasing a new version with these fixes.  
If you have any other problem, open a new issue :)

edoardottt
