### ISSUE TITLE
Unable to run any search 

### ISSUE THREAD

**Issue by NjengaKelvin** [edoardottt/twitterbot2#44]
hi,
When I attempt to run any of the options, (eg `python twitterbot2.py -t = '@ikoworske')`, I receive below error message. Could there be something that I am missing?

Traceback (most recent call last):
  File "C:\Util\Environments\twitterbot2\twitterbot2.py", line 578, in <module>
    main()
  File "C:\Util\Environments\twitterbot2\twitterbot2.py", line 539, in main
    bot = create_bot(logger)
  File "C:\Util\Environments\twitterbot2\twitterbot2.py", line 103, in create_bot
    if secretss["access_token"] is None or secretss["access_token_secret"] is None:
TypeError: string indices must be integers

**Comment by edoardottt** [comment]
Hi @NjengaKelvin ! Thanks for your submission.  
You are using it in the wrong way, the `-t` flag does not require a string to be passed as input.  
With `python twitterbot2.py -t` the bot will like and retweet its timeline and the home of your user. 

See the README.md file for all the informations you need :)

Anyway I'm here if you need help.

**Comment by edoardottt** [comment]
@NjengaKelvin let me know if you are able to run it, I'm closing the issue, if you want to understand better twitterbot2 just DM or email me, if you encounter a bug, open a new issue ! :)
Have a good day

**Comment by NjengaKelvin** [comment]
Thanks, will let you know
